# Generated by Django 4.0.1 on 2022-02-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_coursemodel_slug'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstudentmodel',
            name='couese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassStudentModel', to='courses.coursemodel'),
        ),
    ]
